name: Daily User Stats Refresh

on:
  schedule:
    - cron: '1 0 * * *'  # 00:01 UTC = 5:01 PM PST
  workflow_dispatch:     # optional manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Run refresh_user_stats
        run: node refresh_user_stats.js
        working-directory: ./scripts
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
