name: Update Supabase User Stats

on:
  schedule:
    - cron: '1 1 * * *'  # 5:01 PM PST (1:01 AM UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install supabase pandas

      - name: Run update script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python update_user_stats.py
